### ISSUE TITLE
KeyError {0} not in {1}

### ISSUE THREAD

**Issue by alexbacita** [icebert/eccDNA_RCA_nanopore#8]
Is this basically saying that it cannot deal with unmapped reads? How can I fix this? Thanks!

Traceback (most recent call last):
  File "/mnt/c/linuxdata/eccDNA_RCA_nanopore/./eccDNA_RCA_nanopore.py", line 577, in <module>
    cs = ConsensusSequence(fastq, genome, read).callConsensus()
  File "/mnt/c/linuxdata/eccDNA_RCA_nanopore/./eccDNA_RCA_nanopore.py", line 512, in callConsensus
    reference = self._getReference()
  File "/mnt/c/linuxdata/eccDNA_RCA_nanopore/./eccDNA_RCA_nanopore.py", line 507, in _getReference
    s = self.genome[interval.chr][interval.start:interval.end+1]
  File "/home/abacita/miniconda3/lib/python3.10/site-packages/pyfaidx/__init__.py", line 1124, in __getitem__
    raise KeyError("{0} not in {1}.".format(rname, self.filename))
KeyError: '0bac1663-45c1-420a-b923-f7cbb7736d05 not in hg38.fa.'

**Comment by icebert** [comment]
Hi Alexandru,

Yes, unmapped reads should not be included. If you use minimap2 for the mapping, by default, minimap2 does not output unmapped reads in paf format. If you use other mappers, you need to remove the unmapped reads first.

**Comment by alexbacita** [comment]
Thanks! I've used: minimap2 -x map-ont -c --secondary=no -t 18 hg38_index.mmi merged_pass.fastq.gz > alignment.paf

However, my merged_pass.fastq.gz file is merged from two different sequencing runs of the same sample. Wondering if that has anything to do with it. I'll try some troubleshooting but please let me know if you spot anything wrong in the above command.

**Comment by icebert** [comment]
The minimap2 command is correct. I guess it's because of running eccDNA_RCA_nanopore.py --fastq should be the reads fastq file instead of the hg38.fa

**Comment by alexbacita** [comment]
eccDNA_RCA_nanopore.py command is the following: ./eccDNA_RCA_nanopore.py --fastq merged_pass.fastq --paf alignment.paf --info info.tsv --seq seq.fa --var var.tsv --reference hg38.fa

Tried it on test files/other datasets and worked fine. Problem seems to be input data I guess - thanks for the quick responses, much appreciated!

**Comment by alexbacita** [comment]
Full error below - will come back if/when fixed but any other ideas please let me know

Traceback (most recent call last):
  File "/home/abacita/miniconda3/lib/python3.10/site-packages/pyfaidx/__init__.py", line 1122, in __getitem__
    return self.records[rname]
KeyError: '0bac1663-45c1-420a-b923-f7cbb7736d05'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/data/W3_4h_T7/W3_4h_T7/20240412_1515_MN39669_FAX91881_924419b0/./eccDNA_RCA_nanopore.py", line 577, in <module>
    cs = ConsensusSequence(fastq, genome, read).callConsensus()
  File "/mnt/c/data/W3_4h_T7/W3_4h_T7/20240412_1515_MN39669_FAX91881_924419b0/./eccDNA_RCA_nanopore.py", line 512, in callConsensus
    reference = self._getReference()
  File "/mnt/c/data/W3_4h_T7/W3_4h_T7/20240412_1515_MN39669_FAX91881_924419b0/./eccDNA_RCA_nanopore.py", line 507, in _getReference
    s = self.genome[interval.chr][interval.start:interval.end+1]
  File "/home/abacita/miniconda3/lib/python3.10/site-packages/pyfaidx/__init__.py", line 1124, in __getitem__
    raise KeyError("{0} not in {1}.".format(rname, self.filename))
KeyError: '0bac1663-45c1-420a-b923-f7cbb7736d05 not in hg38.fa.'

**Comment by alexbacita** [comment]
Hello @icebert so I've found the read above '0bac1663-45c1-420a-b923-f7cbb7736d05' and it's sequence is 938bp aligning very well > 95% identity on blast. The mapq score in the .paf file is also >= 30 - any ideas why the pipeline crashes? 

I have even tried to exclude it completely from the .paf file and I get the same error. So the problem seems to be the raw fastq read?


@0bac1663-45c1-420a-b923-f7cbb7736d05 runid=f12cab6148ebdb30094b8b259eec22ed12a8f433 read=50384 ch=291 start_time=2024-04-13T07:04:08.493135+01:00 flow_cell_id=FAX91881 protocol_group_id=W3_4h_T7 sample_id=W3_4h_T7 parent_read_id=0bac1663-45c1-420a-b923-f7cbb7736d05 basecall_model_version_id=dna_r10.4.1_e8.2_400bps_sup@v4.2.0
CTTTTTTATGTGTCCTGTTATTTCGTTCAGTTACGTATTGCTAGGAAAGAGAGCAAAGCCTTTATTTTCATTGTCCATTTCCTCTGATTCCTCTTTCCAAACTGGGCATTTTTGTGCTGGAAAGAAATCCTGAATGTTGATGCGATGCTGTGTGATCATCTCTTGGGTAGTCATTTTCCAAATAATTTCTTGGAGTACCGACACTCGTCGTTCTTTCAGGGACCCCTGGGGGCAGTTGGTATATTATACATGTATGAGTTTTTAGATGGCTCCTCTCTCTCAGGTTATTTCTGCTGTTTCTGTTAAGATCACACAGCATCGCATCAACATTCAGGATTTCTTTCCAGCACAAAAATGCCCAGTTTGGAAAGAGGAGACGAAAGAAAATGGACAATGAAAAATAAAGGCTTTGCTCTTCCTTAAATAGTAGAGGCGCTGGGATGACAGAATGTGCTGGCTGCTTGACTCGGGGAGCCTTGAGTGCACTCGGTGCTGGCTGGCTAACATGGTCTGACTGTGTCCCCACCCAAATCTCATCTTGAATTGTCCCATAATCCCCACATGTTGGGGGAGTGACACGGTGGGAGGTAATTGCATCACAGGGGTGGATACCCCATGCTGTTCTCATGATAGTGACCGAGTTCTCACAAGATCTGACGGTTTTATCATGGGCTTTTCCCCCTTTGCTCGGCACTTCTCCTTGCTGCCGCCACGTGAAGAAGAACATGTTTGCTTCCCCTTCTGCTGTGATTGTAAGTTTCCTGAGGCCTCCTCAGCCCTGCAGAACTGTGAGTCCATTAAACCTCTTTCCTTCATAAATTACCCAGTCTTGGGTGTGTCTTTATTAGCAGCGTGAGAACAGACGAATACACCTGCCTTGGCGGTGCTGTGACACATGGCCTGTTACTCACGTTCCCATCTGATTAAGCAATACGTGG
+
%%&&(11-+**((%%%%%&%$%&&(,---42210/0001454322220/0+++..324445685543452110/010122(63200//1333554658656555566434458655556665433332233453321121020--../34444322222344455530/.../0123465442211021246432...,+,,,.21---,,../5321213554545333363331112120///.////121100/0011253222222443455656564532211123567764334464210/0/00125555621///0022120121210///22444553210/123224442224333445645442/..+*+++/003232221100///,*,,,--4335643)))/,,-////...-.00122////032221224321001357777763221132/0000555333223323421.../03566776720./../11254-----9:;<?BBABCCCHFEGEB;::::<87752000-----;>?C>A=<<989656642+*++(((((-4:;>99775773200011334999940----2699;<=@BAEGA@@>=::9865,))))-8:;AA:::::>?;50---.045322122337678666>;<<4-0875444444433333678::3....,----77632100/..---,-3689:<;:88996555567889?>=;;6<=@@@??>><8/..++,,,3349:::;<=<<<<<;;:::====<<<<=>?=:66555789:<<=A>77654532.--./599786))),2222456:986443---,,00035577544331101257753333)(('&'&&&&%%'+*+((((,.(0222110.../03100))%$

**Comment by alexbacita** [comment]
Hello @icebert I have looked into the read ID causing the problem and it seems fairly normal. I have even blasted its 938 bp sequence and it maps with 98% identity to the human genome. 

Can you spot anything wrong from the paf file? I thought it might be the mapping quality of 1 but I have removed those and I still get the same error.
![IMG_6693](https://github.com/icebert/eccDNA_RCA_nanopore/assets/101040495/98e70c91-2f9c-4b27-a0b8-c357f59e9d7f)

**Comment by icebert** [comment]
Hi Alexandru, for the PAF file, the 6th column should be the chromosome name, not the read name. Only the 1st column is the read name. It seems the reads were mapped to the reads themselves, not to hg38.fa.

You may check your command for generating the hg38_index.mmi, which should use hg38.fa as input, not the reads as input.

https://github.com/lh3/miniasm/blob/master/PAF.md

**Comment by alexbacita** [comment]
That was it! Much appreciated, thanks!
